DROP TABLE IF EXISTS instruktorzy CASCADE;
DROP TABLE IF EXISTS instruktorzy_stopnie CASCADE;
DROP TABLE IF EXISTS stopnie CASCADE;
DROP TABLE IF EXISTS ubezpieczenia CASCADE;
DROP TABLE IF EXISTS dostepnosc_sezon CASCADE;
DROP TABLE IF EXISTS klienci CASCADE;
DROP TABLE IF EXISTS dzieci_odznaki CASCADE;
DROP TABLE IF EXISTS odznaki CASCADE;
DROP TABLE IF EXISTS dzieci_grupy CASCADE;
DROP TABLE IF EXISTS grupy CASCADE;
DROP TABLE IF EXISTS harmonogram CASCADE;
DROP TABLE IF EXISTS stawki_stopnie;
DROP TABLE IF EXISTS sporty;
DROP TABLE IF EXISTS lista_oczekujacych CASCADE;
DROP FUNCTION IF EXISTS umow_konkretny (id_in integer, dataa date, godzina_od integer, godzina_do integer, id_kli integer) CASCADE;
DROP FUNCTION IF EXISTS wstaw_klienta(varchar(30), varchar(30), numeric(9), date) CASCADE;
DROP FUNCTION IF EXISTS wstaw_nieobecnosci(int, date, numeric(2), numeric(2)) CASCADE;
DROP FUNCTION IF EXISTS umow_konkretny(int, date, int, int, int, int) CASCADE;
DROP FUNCTION IF EXISTS id_klienta(varchar(30), varchar(30)) CASCADE;
DROP FUNCTION IF EXISTS umow_dowolny( klient integer, dzien date, h_od integer, h_do integer) CASCADE;
DROP FUNCTION IF EXISTS wyswietl_harmonogram(dzien date) CASCADE;
DROP FUNCTION IF EXISTS umow_dowolny(int, date, int, int, int) CASCADE;
DROP FUNCTION IF EXISTS znajdz_instruktora(im varchar(30)) CASCADE;
DROP FUNCTION IF EXISTS wyswietl_poczekalnie(id_odz int, dzien date) CASCADE;
DROP FUNCTION IF EXISTS wyswietl_poczekalnie() CASCADE;
DROP FUNCTION IF EXISTS wyswietl_grupy(dzien date) CASCADE;
DROP FUNCTION IF EXISTS ile_dzieci(grupa int) CASCADE;
DROP FUNCTION IF EXISTS dodaj_nieobecnosc(instruktor int, dzien date, h_od numeric(2), h_do numeric(2)) CASCADE;
DROP FUNCTION IF EXISTS max_stopien(instruktor int, sport int) CASCADE;
DROP FUNCTION IF EXISTS wyplata(instruktor int, dzien date) CASCADE;
DROP FUNCTION IF EXISTS b_grupy_insert() CASCADE;
DROP FUNCTION IF EXISTS aft_grupy_insert() CASCADE;
DROP FUNCTION IF EXISTS licznosc_grupy(int) CASCADE;
DROP FUNCTION IF EXISTS max_odznaka(int, int) CASCADE;
DROP FUNCTION IF EXISTS lista_oczekujacych_ins() CASCADE;
DROP FUNCTION IF EXISTS harmonogram_add() CASCADE;
DROP FUNCTION IF EXISTS dzieci_grupy_del() CASCADE;
DROP FUNCTION IF EXISTS dostepnosc_sezon_tr() CASCADE;
DROP FUNCTION IF EXISTS odznaki_immutability() CASCADE;
DROP FUNCTION IF EXISTS dzieci_grupy_insert() CASCADE;
DROP FUNCTION IF EXISTS dodaj_do_grupy(int, int, date) CASCADE;
DROP FUNCTION IF EXISTS dodaj_grupe(int, int, date, int, int) CASCADE;
DROP FUNCTION IF EXISTS nadaj_odznake(int, int, date) CASCADE;
DROP FUNCTION IF EXISTS archiwizuj_liste_oczekujacych();
DROP FUNCTION IF EXISTS currentdate();
DROP FUNCTION IF EXISTS deactivate_and_delete();
DROP FUNCTION IF EXISTS usun_zajecia( id_instr int, p_data date, godz numeric(2)) CASCADE;
DROP FUNCTION IF EXISTS dell();
DROP FUNCTION IF EXISTS har();
DROP FUNCTION IF EXISTS instruktor_grupa(int);
DROP FUNCTION IF EXISTS wyswietl_dzieci_grupy(int);
DROP RULE IF EXISTS instruktorzy_delete ON instruktorzy CASCADE;
DROP RULE IF EXISTS grupy_update ON grupy CASCADE;
DROP RULE IF EXISTS dostepnosc_sezon_rule1 ON dostepnosc_sezon CASCADE;
DROP RULE IF EXISTS dostepnosc_sezon_rule2 ON dostepnosc_sezon CASCADE;
DROP RULE IF EXISTS klienci_delete ON klienci CASCADE;
DROP INDEX IF EXISTS klienci_idx;
DROP INDEX IF EXISTS instruktorzy_idx;